# Generated by Django 5.0.4 on 2024-04-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('subtypes', models.CharField(max_length=500)),
                ('rules', models.CharField(max_length=5000)),
                ('attack_names', models.CharField(max_length=500)),
            ],
        ),
    ]
